name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: android debug
      - uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: bin/*.apk
